### ISSUE TITLE
Render changes

### ISSUE THREAD

**Issue by mahmoud-eskandari** [oov/psd#2]
Can't render changes because `PSD.Picker` object not updated after modify layers
,is it possible?

**Comment by oov** [comment]
Editing is currently not supported in this package so you can't it.

**Comment by mahmoud-eskandari** [comment]
I not to find a layer an replace it's image with an other image and render it
can you help me to finding a library or suggest me the solution for this issue?

Thank's so much♥

**Comment by oov** [comment]
I don't know the package that is possible in Go.
Rendering a PSD file is a very complicated task in generally.
So I think there are almost no libraries that can do it without problems.

I found something like this. (but I have never used it.)
https://www.molecular-matters.com/products_psd_sdk.html
