### ISSUE TITLE
Panic on psd.decodePackBitsPerLine()

### ISSUE THREAD

**Issue by samsamm777** [oov/psd#3]
When decoding some (not all) PSD's we get a crash in the oov/psd library.

```
panic: runtime error: slice bounds out of range

goroutine 525 [running]:
github.com/oov/psd.decodePackBitsPerLine(0xc0049107f0, 0xf1b30, 0x2d6900, 0xc000f41e5c, 0x2f94, 0xeb2c8, 0xc0002e6d58, 0x1ef, 0x5d0)
	/Users/sam.hudson/.gvm/pkgsets/go1.11/global/pkg/mod/github.com/oov/psd@v0.0.0-20181223142219-ada9a92c125a/compress_other.go:82 +0x265
github.com/oov/psd.decodePackBits.func1(0xc0000b13f0, 0xc0049107f0, 0xf1b30, 0x2d6900, 0xc000ee98dc, 0x5b514, 0x143848, 0xc0002e6d58, 0x1ef, 0x5d0)
	/Users/sam.hudson/.gvm/pkgsets/go1.11/global/pkg/mod/github.com/oov/psd@v0.0.0-20181223142219-ada9a92c125a/compress_other.go:63 +0xb4
created by github.com/oov/psd.decodePackBits
	/Users/sam.hudson/.gvm/pkgsets/go1.11/global/pkg/mod/github.com/oov/psd@v0.0.0-20181223142219-ada9a92c125a/compress_other.go:61 +0x468
```

**Comment by oov** [comment]
Could you upload PSD file for investigation?

**Comment by samsamm777** [comment]
Unfortunately we cant share our PSD's. However we are trying to replicate the issue with a PSD which can be shared, but it might take some time to reproduce.

**Comment by samsamm777** [comment]
I'm going to close this. We have since found out our customer is using Sketchbook Pro to generate the PSD, which we do not support.

**Comment by oov** [comment]
Thank you for the very important information!
With Autodesk SketchBook, I could reproduce the problem.
This issue is important to me so I will reopen it.

**Comment by oov** [comment]
To decode file, it needed an implementation of "noop" on PackBits that was not mentioned in the information I referred at that time.
Thus this problem is completely my fault.
Sorry!

**Comment by samsamm777** [comment]
@oov Thank you for fixing that! Amazing work.
