### ISSUE TITLE
PSD decode error

### ISSUE THREAD

**Issue by samsamm777** [oov/psd#5]
Since the PR which fixes a null pointer reference was merged (https://github.com/oov/psd/pull/4) errors for a malformed PSD are correctly handled. However, i dont know why the PSD produces errors. I am using Photoshop 2019 CC. It seems the error is caused by a layer which has a vector mask on it. 

If you could give me your email address, I can supply a sample PSD file which exhibits the problem.

The error returned is... `psd: layer mask / adjustment layer data read size mismatched. expected 28 actual 45`

**Comment by oov** [comment]
That would be great, please send file to ilovevipper@gmail.com.
I will investigate this problem.

**Comment by samsamm777** [comment]
Thanks! email sent.

**Comment by oov** [comment]
[PSD specification document](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_13084) describes `Layer mask data: See See Layer mask / adjustment layer data for structure. Can be 40 bytes, 24 bytes, or 4 bytes if no layer mask`, but your file is 32bytes(structure size info 4 bytes + data 28 bytes).
![image](https://user-images.githubusercontent.com/270909/60456981-d0d16000-9c75-11e9-9b0a-f8e4dc9d1c6d.png)
I believe in the spec and implement it, but the actual file seems to be different from the spec.

https://github.com/oov/psd/tree/issue5
I fixed the problem based on that information, so please try it this branch.

**Comment by oov** [comment]
BTW, as you might already know, English is not a native language for me.
So I may misreading the specification document.
Please let me know if you have noticed something.
Thanks!

**Comment by samsamm777** [comment]
Your english is very good! It's better than my japanese! 😂 

Thanks for building out a fixed branch. I will test it and see if it works for us. I will also have a read through the specification and see if what you are saying about the expected data is those sizes specified.
