### ISSUE TITLE
Is it possible to get the properties of a "text layer" ? 

### ISSUE THREAD

**Issue by mrold** [oov/psd#6]
Such as "font", "color", "font-size", "font-weight" and so on.

**Comment by oov** [comment]
There is no text layer analyzer in this package, so it is a bit cumbersome to get the data you need.

http://fileformats.archiveteam.org/wiki/Photoshop_Text_Engine_Data

It seems text layer has additional data named "Txt2".
I haven't tried it but if it really exists, you can access it by `psd.Layer.AdditionalLayerInfo["Txt2"]`.
Hence you can get the necessary data if you analyze it by yourself.

**Comment by mrold** [comment]
Ok, thank you for your help.
