### ISSUE TITLE
Layer Comps

### ISSUE THREAD

**Issue by bcvery1** [oov/psd#7]
Is it possible to get Layer Comps?

**Comment by oov** [comment]
At this time, processing related to Layer Comps is not implemented in this package.
But related information seems to be stored in [Image Resource ID 0x0429](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/).
I can't find detailed specifications but you can get the information you need if you analyze the RAW data yourself.
```go
	file, err := os.Open("some.psd")
	if err != nil {
		log.Fatalln(err)
	}
	defer file.Close()

	img, _, err := psd.Decode(file, &psd.DecodeOptions{SkipMergedImage: true})
	if err != nil {
		log.Fatalln(err)
	}

	log.Println("Layer Comps RAW Data Size:", len(img.Config.Res[0x0429].Data))
```

**Comment by bcvery1** [comment]
Thanks for the detailed reply!  That's really helpful.
